version: '3.9'

services:
  db:
    image: postgres:15
    container_name: meufinanceiro_db
    restart: always
    environment:
      POSTGRES_DB: meufinanceiro
      POSTGRES_USER: meufinanceiro_user
      POSTGRES_PASSWORD: meufinanceiro_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: meufinanceiro_backend
    command: gunicorn meufinanceiro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: 